// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: serial.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SerialEmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SerialEmptyRequest) Reset() {
	*x = SerialEmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serial_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SerialEmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialEmptyRequest) ProtoMessage() {}

func (x *SerialEmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serial_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialEmptyRequest.ProtoReflect.Descriptor instead.
func (*SerialEmptyRequest) Descriptor() ([]byte, []int) {
	return file_serial_proto_rawDescGZIP(), []int{0}
}

// The request message containing the user's name.
type SerialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *SerialRequest) Reset() {
	*x = SerialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serial_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SerialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialRequest) ProtoMessage() {}

func (x *SerialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serial_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialRequest.ProtoReflect.Descriptor instead.
func (*SerialRequest) Descriptor() ([]byte, []int) {
	return file_serial_proto_rawDescGZIP(), []int{1}
}

func (x *SerialRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type SerialReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profiles []*Profile `protobuf:"bytes,1,rep,name=Profiles,proto3" json:"Profiles,omitempty"`
}

func (x *SerialReply) Reset() {
	*x = SerialReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serial_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SerialReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialReply) ProtoMessage() {}

func (x *SerialReply) ProtoReflect() protoreflect.Message {
	mi := &file_serial_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialReply.ProtoReflect.Descriptor instead.
func (*SerialReply) Descriptor() ([]byte, []int) {
	return file_serial_proto_rawDescGZIP(), []int{2}
}

func (x *SerialReply) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type Profile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string  `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Path     string  `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
	Mode     string  `protobuf:"bytes,3,opt,name=Mode,proto3" json:"Mode,omitempty"`
	BaudRate *string `protobuf:"bytes,4,opt,name=BaudRate,proto3,oneof" json:"BaudRate,omitempty"`
	Parity   *string `protobuf:"bytes,5,opt,name=Parity,proto3,oneof" json:"Parity,omitempty"`
	Stopbits *string `protobuf:"bytes,6,opt,name=Stopbits,proto3,oneof" json:"Stopbits,omitempty"`
}

func (x *Profile) Reset() {
	*x = Profile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_serial_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_serial_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_serial_proto_rawDescGZIP(), []int{3}
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Profile) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Profile) GetBaudRate() string {
	if x != nil && x.BaudRate != nil {
		return *x.BaudRate
	}
	return ""
}

func (x *Profile) GetParity() string {
	if x != nil && x.Parity != nil {
		return *x.Parity
	}
	return ""
}

func (x *Profile) GetStopbits() string {
	if x != nil && x.Stopbits != nil {
		return *x.Stopbits
	}
	return ""
}

var File_serial_proto protoreflect.FileDescriptor

var file_serial_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x23, 0x0a, 0x0d,
	0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x3a, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x2b, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0xc9, 0x01,
	0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x08, 0x42, 0x61, 0x75, 0x64, 0x52, 0x61, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x42, 0x61, 0x75, 0x64, 0x52,
	0x61, 0x74, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x69, 0x74, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x06, 0x50, 0x61, 0x72, 0x69, 0x74, 0x79,
	0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x53, 0x74, 0x6f, 0x70, 0x62, 0x69, 0x74, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x08, 0x53, 0x74, 0x6f, 0x70, 0x62, 0x69, 0x74,
	0x73, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x42, 0x61, 0x75, 0x64, 0x52, 0x61, 0x74,
	0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x50, 0x61, 0x72, 0x69, 0x74, 0x79, 0x42, 0x0b, 0x0a, 0x09,
	0x5f, 0x53, 0x74, 0x6f, 0x70, 0x62, 0x69, 0x74, 0x73, 0x32, 0x83, 0x01, 0x0a, 0x06, 0x53, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x12, 0x3e, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x12, 0x1a, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x53, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x53, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x12, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x53, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x2e, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42,
	0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_serial_proto_rawDescOnce sync.Once
	file_serial_proto_rawDescData = file_serial_proto_rawDesc
)

func file_serial_proto_rawDescGZIP() []byte {
	file_serial_proto_rawDescOnce.Do(func() {
		file_serial_proto_rawDescData = protoimpl.X.CompressGZIP(file_serial_proto_rawDescData)
	})
	return file_serial_proto_rawDescData
}

var file_serial_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_serial_proto_goTypes = []interface{}{
	(*SerialEmptyRequest)(nil), // 0: serial.SerialEmptyRequest
	(*SerialRequest)(nil),      // 1: serial.SerialRequest
	(*SerialReply)(nil),        // 2: serial.SerialReply
	(*Profile)(nil),            // 3: serial.Profile
}
var file_serial_proto_depIdxs = []int32{
	3, // 0: serial.SerialReply.Profiles:type_name -> serial.Profile
	0, // 1: serial.Serial.GetSerial:input_type -> serial.SerialEmptyRequest
	1, // 2: serial.Serial.SetSerial:input_type -> serial.SerialRequest
	2, // 3: serial.Serial.GetSerial:output_type -> serial.SerialReply
	2, // 4: serial.Serial.SetSerial:output_type -> serial.SerialReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_serial_proto_init() }
func file_serial_proto_init() {
	if File_serial_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_serial_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SerialEmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serial_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SerialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serial_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SerialReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_serial_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Profile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_serial_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_serial_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_serial_proto_goTypes,
		DependencyIndexes: file_serial_proto_depIdxs,
		MessageInfos:      file_serial_proto_msgTypes,
	}.Build()
	File_serial_proto = out.File
	file_serial_proto_rawDesc = nil
	file_serial_proto_goTypes = nil
	file_serial_proto_depIdxs = nil
}
